CREATE TABLE JOGADOR(
    PSEUDONIMO	VARCHAR (10) NOT NULL PRIMARY KEY,
    NOME		VARCHAR (25) NOT NULL,
    SENHA		VARCHAR (6)  NOT NULL
);

CREATE TABLE NIVEL(
	NIVEL		NUMERIC (3)	 NOT NULL PRIMARY KEY,	
	PONTOS		NUMERIC (5)	 NOT NULL,
	BONUS		NUMERIC (5)	 NOT NULL,	
	NOMEPSEUD	VARCHAR (10) NOT NULL FOREIGN KEY REFERENCES JOGADOR(PSEUDONIMO)
);

INSERT INTO JOGADOR
VALUES ('dudu', 'Eduardo', 'edu123')	   

INSERT INTO NIVEL
VALUES (10, 200, 200, 'dudu')

/* RESPOSTA EXERCICIOS
1. Mostre somente o nome do jogador 
πPSEUDONIMO (JOGADOR)*/
SELECT NOME FROM JOGADOR

/* 2. Mostre pseudonimo mais nome 
πPSEUDONIMO, NOME (JOGADOR)*/
SELECT PSEUDONIMO, NOME FROM JOGADOR

/* 3. Mostre nome e senha 
πNOME, SENHA (JOGADOR)*/
SELECT PSEUDONIMO, SENHA FROM JOGADOR

/* 4. Mostre somente o nível 
πNIVEL (NIVEL)*/
SELECT NIVEL FROM NIVEL

/* 5. Mostre a pontuação 
πPONTOS (NIVEL)*/
SELECT PONTOS FROM NIVEL

/* 6. Mostre o nível mais pontuação 
πPONTOS, NIVEL (NIVEL)*/
SELECT PONTOS, NIVEL FROM NIVEL

/* 7. Mostre todos os dados da tabela Jogador 
πPSEUDONIMO, NOME, SENHA (JOGADOR)*/
SELECT * FROM JOGADOR

/* 8. Mostre todos os dados da tabela Nivel 
πNIVEL, PONTOS, BONUS, NOMEPSEUD (NIVEL)*/
SELECT * FROM NIVEL

/* 9. Mostre o pseudonimo mais nivel
πPSEUDONIMO, PONTOS (σ JOGADOR.PSEUDONIMO = NIVEL.NOMEPSEUD (JOGADOR x NIVEL)) */
SELECT JOGADOR.PSEUDONIMO, NIVEL.PONTOS FROM JOGADOR JOIN NIVEL
ON NOMEPSEUD = PSEUDONIMO;

/* 10. Mostre pseudonimo mais pontuação e bônus
πPSEUDONIMO, PONTOS, BONUS (σ JOGADOR.PSEUDONIMO = NIVEL.PONTOS,BONUS (JOGADOR x NIVEL))*/
SELECT JOGADOR.PSEUDONIMO, NIVEL.PONTOS,BONUS FROM JOGADOR JOIN NIVEL
ON NOMEPSEUD = PSEUDONIMO;